### ISSUE TITLE
[BUG] Not working in Ubuntu Xenial 16.04

### ISSUE THREAD

**Issue by mxcoder** [vaibhav-sidapara/vagrant-manager#2]
Hi!

I'm just testing out some electron apps, and yours seemed quite useful for me, I downloaded the last available portable version but sadly is not working for me. I've tried other electron apps and they seem to be working fine. Here some of my data:

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
```
```
uname -a
Linux XXXXXXX 4.4.0-45-generic #66-Ubuntu SMP Wed Oct 19 14:12:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```
```
vagrant -v
Vagrant 1.8.6
```

## Expected

For the program to run when executed

## Result

Running `./vagrant-manager` shows absolutely nothing.
Double clicking on the same executable from GUI does nothing either.

**Comment by TheSamsa** [comment]
Worked on my Ubuntu 16.04.
I'll take a look at home, if something is different.

**Comment by vaibhav-sidapara** [comment]
Hi mxcoder,

Appreciate your feedback. 

Regarding your issue `Running ./vagrant-manager shows absolutely nothing.`, this is a tray only app, you shall see a tray icon. 

May I know what desktop environment you are using? It is working fine on 'unity'. I have not tested this app on any other environment. I built this app on Ubuntu 16.04 as well.

**Comment by mxcoder** [comment]
Hey Vaibhav, TheSamsa

I should have said before, I'm using Xenial with gnome-flashback-metacity
So, I had to enable a Notification Area.
Now I see the tray icon!

Thanks for checking.
